### ISSUE TITLE
大佬，这个脚本怎么用？

### ISSUE THREAD

**Issue by barnett2010** [i2534/gjol_music#2]
有没有可能弄成一个exe。把musicxml拖到上面。就直接生成一个gjm文件？

**Comment by barnett2010** [comment]
我看得懂谱。看不懂java

**Comment by i2534** [comment]
很快将有一个网页版的转化工具出来

2018-08-20 

i2534 



发件人：barnett2010 <notifications@github.com>
发送时间：2018-08-19 11:54
主题：Re: [i2534/gjol_music] 大佬，这个脚本怎么用？ (#2)
收件人："i2534/gjol_music"<gjol_music@noreply.github.com>
抄送："Subscribed"<subscribed@noreply.github.com>

我看得懂谱。看不懂java

**Comment by i2534** [comment]
网页版已经出来了 https://i2534.github.io/gjol_music/demo.html
